title: Golden Gate Science Olympiad Invitational - UC Berkeley and Stanford University
email: goldengatescioly@gmail.com
description: >
  Science Olympiad invitational run by UC Berkeley and Stanford University students. Coming 2020.
baseurl: ""
url: ""
github_username:  matthew29tang

markdown: kramdown

collections:
    ggrc:
        output: true
        permalink: /ggrc/:path/
        
plugins:
  - jekyll-redirect-from